version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:1.15.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=GITEADATABASE
      - GITEA__database__USER=GITEADATABASEUSER
      - GITEA__database__PASSWD=GITEADATABASEPASSWORD
    restart: always
    networks:
      - gitea
    volumes:
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    depends_on:
      - db
 
  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=GITEADATABASEROOTPASSWORD
      - MYSQL_USER=GITEADATABASEUSER
      - MYSQL_PASSWORD=GITEADATABASEPASSWORD
      - MYSQL_DATABASE=GITEADATABASE
    networks:
      - gitea
    volumes:
      - ./mysql:/var/lib/mysql